version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -p 8888 -C /app/config/puma.rb
    volumes:
      - /var/tmp
      - .:/app
    depends_on:
      - db
    extends:
      file: ./docker/mysql/password.yml
      service: password
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes: 
      - db_data:/var/lib/mysql
    extends:
      file: ./docker/mysql/password.yml
      service: password
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - app

volumes: 
  db_data: